name: CWCombatLog
version: '1.0.1'
main: cwcombatlog.nl.cWCombatLog.CWCombatLog
api-version: '1.21'
load: STARTUP
authors: [ ColorWave Studio's ]
description: a simple combat log plugin
website: https://colorwave-studios.com/
softdepend: ["PlaceholderAPI"]
commands:
  cwcombatlog:
    description: CWCombatLog reload or help
    usage: /cwcombatlog
    permission: cwcombatlog.admin
  cwcombatlog reload:
    description: CWCombatLog reload
    usage: /cwcombatlog reload
    permission: cwcombatlog.admin
  cwcombatlog help:
    description: CWCombatLog help
    usage: /cwcombatlog help
    permission: cwcombatlog.admin
permissions:
  cwcombatlog.admin:
    description: Allows /cwcombatlog reload
    default: op
  cwcombatlog.bypass:
    description: Bypass command blocking during timer
    default: op
  cwcombatlog.combatlog.bypass:
    default: op